/**
 * AUTO-GENERATED by scripts/codegen.mjs — do not edit manually.
 * Source: src/BCConfig.sol
 */

import type { Address } from "viem";
import type { BcNetworkConfig } from "./types.js";

// Well-known addresses
export const WELL_KNOWN_CREATEX: Address = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed";

// URIs
export const SAFE_HARBOR_V3_URI = "ipfs://bafkreiernns2f4nv2uzvwtzjc2jboyivsu2mixz33y3xo7cvtllsuao6jy";
export const BATTLECHAIN_SAFE_HARBOR_URI = "ipfs://bafkreifgln3ir67woluatpwn3b65gjkrbmoq6jgzzotm3anas3vvq4yp4m";

export const bcTestnet: BcNetworkConfig = {
  chainId: 627,
  caip2: "eip155:627",
  registry: "0x0A652e265336a0296816ac4D8400880E3e537c24",
  factory: "0x2BEe2970f10FDc2aeA28662Bb6f6a501278eBd46",
  attackRegistry: "0xdD029a6374095EEb4c47a2364Ce1D0f47f007350",
  deployer: "0x74269804941119554460956f16Fe82Fbe4B90448",
  createX: "0xf1Ebfaa992854ECcB01Ac1F60e5b5279095cca7F",
  safeHarborUri: "ipfs://bafkreifgln3ir67woluatpwn3b65gjkrbmoq6jgzzotm3anas3vvq4yp4m",
};

// Chain IDs
export const BC_MAINNET_CHAIN_ID = 626;
export const BC_TESTNET_CHAIN_ID = 627;
export const BC_DEVNET_CHAIN_ID = 624;

export function isBattleChain(chainId: number): boolean {
  return (
    chainId === BC_MAINNET_CHAIN_ID ||
    chainId === BC_TESTNET_CHAIN_ID ||
    chainId === BC_DEVNET_CHAIN_ID
  );
}
